language: objective-c

branches:
  only:
    - master

xcode_project: demo/demo.xcodeproj
xcode_scheme: demo
osx_image: xcode7.2

script:
    xcodebuild -project demo/demo.xcodeproj -target demo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO